(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='rootline.ai.v2';
const state={people:new Map(),families:new Map(),selected:null,attachment:null,chat:[],saved:{notes:[],inbox:[],watch:[]}};
const statusOrder=['New','Lead','Approved Candidate','Rejected'];

const tools=[
 {id:'solve',icon:'✦',title:'Solve this person',sub:'Autonomous AI research plan',prompt:'Build an autonomous, evidence-first research plan to solve the biggest unresolved questions for this person. Prioritize the searches, records, repositories, name variants, dates and places that are most likely to produce proof.'},
 {id:'evidence',icon:'▦',title:'Evidence matrix',sub:'Claims × sources × quality',prompt:'Create an evidence matrix for this person. List the key genealogical claims, the evidence currently supporting each claim, source quality, conflicts, missing proof, and a confidence assessment. Do not promote assumptions.'},
 {id:'graph',icon:'⌘',title:'Evidence graph',sub:'People ↔ claims ↔ sources',prompt:'Build a text evidence graph for this person linking people, relationships, claims, sources, dates and conflicts. Highlight weak links and identity-collision risk.'},
 {id:'hypothesis',icon:'🧪',title:'Hypothesis lab',sub:'Keep theories separate',prompt:'Act as a genealogy hypothesis lab. Identify the strongest competing explanations for the unresolved parts of this profile. For each hypothesis give supporting evidence, evidence against it, missing proof, and the exact test that would strengthen or reject it.'},
 {id:'inbox',icon:'⌁',title:'Research inbox',sub:'AI finds before the tree',prompt:'Review this person and propose a research-inbox list of candidate findings or questions that should be investigated before anything is added to the proven tree. Classify each as New lead, needs verification, conflict, or likely rejection.'},
 {id:'dna',icon:'🧬',title:'DNA workspace',sub:'Matches, cM & clustering',prompt:'Open the DNA genealogy workspace for this person. Explain what match data would be most useful, how to cluster it by branch, and how to combine shared cM, shared matches and documentary evidence without overclaiming. If I have not supplied DNA match data, ask me for the exact fields you need.'},
 {id:'famous',icon:'★',title:'Famous connections',sub:'Prove or reject routes',web:true,prompt:'Investigate possible famous or historically notable connections for this person, but use an evidence-first standard. Preserve rejected routes, flag every unproven generation, and prioritize documentary proof over online-tree claims.'},
 {id:'healthhistory',icon:'♥',title:'Family health history',sub:'Evidence, not diagnosis',prompt:'Organize a family health-history research view for this person using only documented family-history facts supplied in the tree or records. Separate reported conditions, documented causes of death, family testimony and unknowns. Do not diagnose or infer medical conditions.'},
 {id:'military',icon:'⚑',title:'Military service',sub:'Branch, unit, conflict & files',web:true,prompt:'Research and audit the military-service picture for this person. Identify likely branch, rank, unit, conflict, enlistment/discharge, pension or service-file routes, and the authoritative records needed to prove each point. Distinguish unit history from proof of the individual’s participation.'},
 {id:'collisions',icon:'◎',title:'Identity collisions',sub:'Catch same-name merges',prompt:'Run an identity-collision audit. Look for same-name people, incompatible ages, places, spouses, children, occupations, military service or timelines that could cause two people to be merged incorrectly. Give a checklist of identifiers needed to distinguish them.'},
 {id:'migration',icon:'⌖',title:'Migration map',sub:'Places through time',prompt:'Reconstruct this person’s migration path from the known timeline. Separate documented residences from inferred movement, identify missing locations/years, and recommend records that can pin down each move.'},
 {id:'relationship',icon:'⛓',title:'Relationship finder',sub:'Path between two people',prompt:'Act as the Rootline relationship finder. Using the selected person as one endpoint, ask me for the other person if I have not named them, then show the relationship path person-by-person and flag every weak or unproven link.'},
 {id:'hints',icon:'💡',title:'Explainable hints',sub:'Why a lead matters',prompt:'Generate explainable research hints for this person. For each hint tell me why it matters, what evidence triggered it, what could make it wrong, and the specific record that would strengthen or disprove it.'},
 {id:'cluster',icon:'◉',title:'Cluster research',sub:'FAN club research',web:true,prompt:'Create a cluster/FAN research plan around this person using siblings, spouses, children, neighbors, witnesses, informants, associates and recurring surnames. Explain which collateral people are most likely to break the brick wall and why.'},
 {id:'context',icon:'◷',title:'Historical context',sub:'Their place in history',web:true,prompt:'Place this person in accurate historical context for the places and dates in their timeline. Clearly separate contextual history from biographical facts about the person, and cite reliable sources for historical claims.'},
 {id:'citations',icon:'§',title:'Citation studio',sub:'Build source citations',prompt:'Act as a genealogy citation studio. Using only source metadata actually present in the selected profile or supplied by me, create clean source citations and identify every missing citation field. Never invent missing archive, volume, page, URL or access-date information.'},
 {id:'watchlist',icon:'◌',title:'Research watchlist',sub:'Prioritize unresolved people',prompt:'Prioritize this person for a research watchlist. Identify the top unresolved questions, what event or new record would make the case move, and a concise trigger/checklist for revisiting the research.'},
 {id:'book',icon:'▤',title:'Family book',sub:'Evidence-first chapter',prompt:'Draft an evidence-first family-book chapter about this person. Make it vivid and readable while clearly labeling uncertainty, family tradition and unresolved claims. End with source notes and a short “what we still do not know” section.'},
 {id:'documentary',icon:'▶',title:'Documentary mode',sub:'Scenes, narration & proof',prompt:'Turn this person’s documented story into a documentary sequence with scenes, narration, visual/source suggestions and transitions. Add an evidence note to each factual beat and do not dramatize uncertain claims as fact.'},
 {id:'oral',icon:'◉',title:'Oral history',sub:'Stories → research clues',prompt:'Act as an oral-history analyst for this person. If I provide family testimony or a transcript, extract claims, names, dates, places and follow-up questions, while labeling testimony as testimony until independently corroborated. If none is supplied, give me the best interview questions for this person’s branch.'},
 {id:'collab',icon:'👥',title:'Collaboration',sub:'Private-safe review bundle',prompt:'Prepare a private-safe collaboration brief for this person that another family researcher could review. Include the research question, proven facts, current hypotheses, conflicts, best sources, next tasks and what should remain private for living people.'},
 {id:'backup',icon:'↺',title:'Backup & GEDCOM',sub:'Preserve your work',local:'saved',prompt:''}
];
const quickPrompts={
 record:'Analyze the attached genealogy record carefully. Extract every useful detail, distinguish direct statements from inference, compare it with the selected person, flag conflicts or identity problems, and tell me what it proves, what it does not prove, and what I should search next.',
 records:'Search the live web for the strongest records that could verify or extend this person. Prioritize original or authoritative sources, explain what each result would prove, preserve citations, and flag identity collisions.',
 audit:'Audit this profile like a careful professional genealogist. Separate proven/direct evidence, strong indirect evidence, hypotheses, conflicts, rejected routes and anything that should not be attached yet.',
 gaps:'Review this person’s timeline and identify the biggest evidence gaps. Give exact record types, date ranges, places, repositories/providers and name variants to search next.'
};

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){localStorage.setItem(STORE,JSON.stringify(state.saved))}
function loadSaved(){try{const x=JSON.parse(localStorage.getItem(STORE)||'{}');state.saved={notes:Array.isArray(x.notes)?x.notes:[],inbox:Array.isArray(x.inbox)?x.inbox:[],watch:Array.isArray(x.watch)?x.watch:[]}}catch{}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2200)}
function showTab(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom-nav [data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='saved')renderSaved();if(id==='records')renderInbox()}

async function gunzipBase64(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw Error('master tree file unavailable');const b64=(await r.text()).replace(/\s+/g,'');const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);if(!('DecompressionStream'in window))throw Error('browser gzip decoding unavailable');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).text()}
function cleanName(s){return String(s||'').replace(/\//g,'').replace(/\s+/g,' ').trim()}
function year(s){const m=String(s||'').match(/(?:^|\D)(1[4-9]\d{2}|20\d{2})(?:\D|$)/);return m?m[1]:''}
function parseGed(text){const P=new Map(),F=new Map();let rec=null,kind='',event='';for(const raw of String(text).split(/\r?\n/)){let m=raw.match(/^0 @([^@]+)@ (INDI|FAM)$/);if(m){kind=m[2];rec=kind==='INDI'?{id:m[1],name:'',birth:'',death:'',birthPlace:'',deathPlace:'',famc:'',fams:[],notes:[]}:{id:m[1],husb:'',wife:'',children:[]};(kind==='INDI'?P:F).set(rec.id,rec);event='';continue}if(!rec)continue;const x=raw.match(/^(\d+)\s+(\S+)(?:\s+(.*))?$/);if(!x)continue;const level=+x[1],tag=x[2],val=(x[3]||'').trim();if(kind==='INDI'){if(level===1){event='';if(tag==='NAME')rec.name=cleanName(val);else if(tag==='FAMC')rec.famc=val.replace(/@/g,'');else if(tag==='FAMS')rec.fams.push(val.replace(/@/g,''));else if(tag==='BIRT')event='BIRT';else if(tag==='DEAT')event='DEAT';else if(tag==='NOTE')rec.notes.push(val)}else if(level===2&&tag==='DATE'){if(event==='BIRT')rec.birth=val;else if(event==='DEAT')rec.death=val}else if(level===2&&tag==='PLAC'){if(event==='BIRT')rec.birthPlace=val;else if(event==='DEAT')rec.deathPlace=val}}else if(kind==='FAM'&&level===1){if(tag==='HUSB')rec.husb=val.replace(/@/g,'');else if(tag==='WIFE')rec.wife=val.replace(/@/g,'');else if(tag==='CHIL')rec.children.push(val.replace(/@/g,''))}}
 state.people=P;state.families=F;for(const p of P.values())enrichPerson(p)}
function personName(id){return state.people.get(id)?.name||'Unknown'}
function enrichPerson(p){const rel=[];if(p.famc){const f=state.families.get(p.famc);if(f?.husb)rel.push({text:`Father: ${personName(f.husb)}`,target:f.husb});if(f?.wife)rel.push({text:`Mother: ${personName(f.wife)}`,target:f.wife})}for(const fid of p.fams){const f=state.families.get(fid);if(!f)continue;const sp=f.husb===p.id?f.wife:f.husb;if(sp)rel.push({text:`Spouse: ${personName(sp)}`,target:sp});for(const c of f.children)rel.push({text:`Child: ${personName(c)}`,target:c})}p.relations=rel;p.events=[];if(p.birth||p.birthPlace)p.events.push([p.birth,'Birth',p.birthPlace].filter(Boolean).join(' • '));if(p.death||p.deathPlace)p.events.push([p.death,'Death',p.deathPlace].filter(Boolean).join(' • '));const by=year(p.birth),dy=year(p.death);p.meta=[[by,dy].filter(Boolean).join('–'),p.birthPlace&&`Born ${p.birthPlace}`,p.deathPlace&&`Died ${p.deathPlace}`].filter(Boolean).join('\n')||'Dates and places not yet established';p.confidence='Unverified';p.sources=p.notes||[];p.gaps=[]}
function fallbackPeople(){const arr=[['bryan','Bryan Olson','b. 2000'],['tony','Tony Cooprider','b. 1974'],['jerry','Jerry Wayne Cooprider','1945–1998'],['donald','Donald Leroy Cooprider','1917–1997'],['wesley','John Wesley Cooprider','1844–1921'],['george','George Peter Cooprider','18th century']];state.people=new Map(arr.map(([id,name,meta])=>[id,{id,name,meta,confidence:'Unverified',relations:[],events:[],gaps:[],sources:[]}]))}
async function loadTree(){try{parseGed(await gunzipBase64('payload/master-tree.ged.gz.b64'))}catch(e){console.warn(e);fallbackPeople();toast('Master tree loaded in safe fallback mode')}const first=[...state.people.values()].find(p=>/bryan.*olson/i.test(p.name))||[...state.people.values()][0];selectPerson(first?.id,false);$('#treeCount').textContent=`${state.people.size.toLocaleString()} people`;renderPeople();renderToolGrid()}

function selected(){return state.people.get(state.selected)||null}
function personForAI(p){if(!p)return null;return {name:p.name,meta:p.meta,confidence:p.confidence,relations:(p.relations||[]).map(x=>x.text),events:p.events||[],gaps:p.gaps||[],sources:p.sources||[]}}
function selectPerson(id,goAI=true){if(!state.people.has(id))return;state.selected=id;const p=selected();$('#selectedName').textContent=p.name;$('#selectedMeta').textContent=p.meta;$('#personPillText').textContent=p.name;renderPersonDetail();renderPeople();renderModalPeople($('#modalSearch')?.value||'');if(goAI){showTab('ai');toast(`${p.name} selected`)}}
function renderPersonDetail(){const p=selected(),box=$('#personDetail');if(!p){box.innerHTML='';return}box.innerHTML=`<article class="person-card-large"><span class="confidence">${esc(p.confidence)}</span><h3>${esc(p.name)}</h3><p>${esc(p.meta)}</p><div class="relationship-row">${(p.relations||[]).slice(0,20).map(r=>`<button data-person="${esc(r.target)}">${esc(r.text)}</button>`).join('')||'<small>No linked relatives parsed yet.</small>'}</div><div class="row-actions"><button class="primary" data-ask-person>Ask AI about this person</button><button data-watch-person>${state.saved.watch.some(w=>w.id===p.id)?'Watching':'Add to watchlist'}</button></div></article>`;box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectPerson(b.dataset.person,false));box.querySelector('[data-ask-person]')?.addEventListener('click',()=>showTab('ai'));box.querySelector('[data-watch-person]')?.addEventListener('click',watchCurrent)}
function filteredPeople(q=''){const n=q.trim().toLowerCase();return [...state.people.values()].filter(p=>!n||p.name.toLowerCase().includes(n)).slice(0,100)}
function personRow(p){return `<button class="person-row" data-person="${esc(p.id)}"><div><b>${esc(p.name)}</b><small>${esc(p.meta)}</small></div><span class="confidence">${esc(p.confidence)}</span></button>`}
function renderPeople(q=$('#treeSearch')?.value||''){const box=$('#peopleList');if(!box)return;box.innerHTML=filteredPeople(q).map(personRow).join('')||'<div class="evidence-rule"><span>No matching people.</span></div>';box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectPerson(b.dataset.person,false))}
function renderModalPeople(q=''){const box=$('#modalPeople');if(!box)return;box.innerHTML=filteredPeople(q).map(personRow).join('');box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{selectPerson(b.dataset.person,false);closeModal('personModal')})}

function openModal(id){$('#'+id)?.classList.remove('hidden');if(id==='personModal'){renderModalPeople();setTimeout(()=>$('#modalSearch')?.focus(),50)}}
function closeModal(id){$('#'+id)?.classList.add('hidden')}
function renderToolGrid(){const box=$('#toolGrid');box.innerHTML=tools.map(t=>`<button class="tool-card" data-tool="${t.id}"><span>${t.icon}</span><b>${esc(t.title)}</b><small>${esc(t.sub)}</small></button>`).join('');box.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>runTool(b.dataset.tool))}
function runTool(id){const t=tools.find(x=>x.id===id);if(!t)return;if(t.local==='saved'){showTab('saved');return}if(t.id==='record'&&!state.attachment){$('#attachmentInput').click();toast('Attach a record, then tap Analyze record');return}showTab('ai');if(t.web)$('#webMode').checked=true;sendAI(t.prompt,t.title)}

function addMessage(role,text,sources=[],model='',saveable=false){const box=$('#messages');const a=document.createElement('article');a.className=`message ${role==='user'?'user-message':'ai-message'}`;if(role!=='user'){const mark=document.createElement('div');mark.className='msg-mark';mark.textContent='✦';a.appendChild(mark)}const body=document.createElement('div');const p=document.createElement('p');p.textContent=text;body.appendChild(p);if(sources?.length){const sl=document.createElement('div');sl.className='source-list';sources.slice(0,12).forEach((s,i)=>{const x=document.createElement('a');x.href=s.url;x.target='_blank';x.rel='noopener';x.textContent=s.title||`Source ${i+1}`;sl.appendChild(x)});body.appendChild(sl)}if(role!=='user'&&model){const meta=document.createElement('div');meta.className='source-list';const m=document.createElement('span');m.textContent=model;m.style.cssText='font-size:7px;color:#777';meta.appendChild(m);if(saveable){const b=document.createElement('button');b.className='status-btn';b.textContent='Save to research inbox';b.onclick=()=>saveAIToInbox(text);meta.appendChild(b)}body.appendChild(meta)}a.appendChild(body);box.appendChild(a);box.scrollTop=box.scrollHeight}
function clearChat(){state.chat=[];$('#messages').innerHTML='<article class="message ai-message"><div class="msg-mark">✦</div><div><p>Conversation cleared. Your saved research, notes and family tree were not changed.</p></div></article>'}

async function sendAI(text,label=''){text=String(text||'').trim();if(!text)return;const p=selected();addMessage('user',label?`${label}: ${text}`:text);state.chat.push({role:'user',content:text});$('#sendBtn').disabled=true;$('#modelStatus').textContent=$('#webMode').checked?'Running live web research…':'Reasoning over your evidence…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),110000);try{const r=await fetch('/api/rootline-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text,mode:$('#webMode').checked?'web':'reason',person:personForAI(p),history:state.chat.slice(0,-1),attachment:state.attachment}),signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.detail||data.error||`AI request failed (${r.status})`),{setupHint:data.setupHint});const answer=data.text||'Rootline AI returned no text.';addMessage('assistant',answer,data.sources||[],data.model||'',true);state.chat.push({role:'assistant',content:answer});$('#modelStatus').textContent=`Connected • ${data.model||'AI Gateway'}`;if(state.attachment)toast('Record analyzed — attachment stays available until removed')}catch(e){const msg=e.name==='AbortError'?'The AI request took too long. Try again.':`${e.message}${e.setupHint?`\n\n${e.setupHint}`:''}`;addMessage('assistant',msg,[],'',false);$('#modelStatus').textContent='AI connection needs attention'}finally{clearTimeout(timer);$('#sendBtn').disabled=false}}

async function chooseFile(file){if(!file)return;const max=9*1024*1024;if(file.size>max){toast('Please use a file under 9 MB');return}let data='';if(file.type.startsWith('text/')||/\.(txt|ged|gedcom)$/i.test(file.name)){data=await file.text();state.attachment={name:file.name,mediaType:'text/plain',data}}else{data=await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(file)});state.attachment={name:file.name,mediaType:file.type||'application/octet-stream',data}}renderAttachment();renderRecordCurrent();toast(`${file.name} attached`)}
function renderAttachment(){const on=!!state.attachment;$('#attachmentBar').classList.toggle('hidden',!on);$('#attachmentName').textContent=on?state.attachment.name:''}
function renderRecordCurrent(){const box=$('#recordCurrent');if(!state.attachment){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<b>${esc(state.attachment.name)}</b><small>${esc(state.attachment.mediaType)} • ready for AI analysis</small><div class="row-actions"><button class="primary" id="analyzeCurrent">Analyze with Rootline AI</button><button id="removeCurrent">Remove</button></div>`;$('#analyzeCurrent').onclick=()=>{showTab('ai');sendAI(quickPrompts.record,'Analyze record')};$('#removeCurrent').onclick=removeAttachment}
function removeAttachment(){state.attachment=null;$('#attachmentInput').value='';renderAttachment();renderRecordCurrent()}
function saveAIToInbox(detail){const p=selected();state.saved.inbox.unshift({id:Date.now(),title:`AI finding — ${p?.name||'General research'}`,detail,status:'New',personId:p?.id||null,created:new Date().toISOString()});save();renderInbox();toast('Saved to research inbox')}
function renderInbox(){const box=$('#inboxList'),arr=state.saved.inbox;$('#inboxCount').textContent=`${arr.length} item${arr.length===1?'':'s'}`;box.innerHTML=arr.map(x=>`<article class="inbox-item" data-id="${x.id}"><header><b>${esc(x.title)}</b><button class="status-btn" data-cycle>${esc(x.status||'New')}</button></header><p>${esc(x.detail)}</p><div class="row-actions"><button data-ai-inbox>Ask AI to review</button><button data-delete>Remove</button></div></article>`).join('')||'<div class="evidence-rule"><span>No research-inbox items yet. Save an AI answer here before promoting anything into your genealogy.</span></div>';box.querySelectorAll('.inbox-item').forEach(el=>{const id=Number(el.dataset.id),item=arr.find(x=>x.id===id);el.querySelector('[data-cycle]').onclick=()=>{const i=statusOrder.indexOf(item.status);item.status=statusOrder[(i+1)%statusOrder.length];save();renderInbox()};el.querySelector('[data-delete]').onclick=()=>{state.saved.inbox=arr.filter(x=>x.id!==id);save();renderInbox()};el.querySelector('[data-ai-inbox]').onclick=()=>{showTab('ai');sendAI(`Review this research-inbox item in context. Decide what evidence would verify or reject it, and do not treat it as fact yet.\n\n${item.title}\n${item.detail}`,'Inbox review')}})}

function watchCurrent(){const p=selected();if(!p)return;const i=state.saved.watch.findIndex(w=>w.id===p.id);if(i>=0){state.saved.watch.splice(i,1);toast('Removed from watchlist')}else{state.saved.watch.push({id:p.id,name:p.name});toast('Added to research watchlist')}save();renderPersonDetail();renderSaved()}
function renderSaved(){renderNotes();renderWatch();$('#watchCount').textContent=`${state.saved.watch.length} people`;$('#noteCount').textContent=`${state.saved.notes.length} notes`}
function renderNotes(){const box=$('#notesList');box.innerHTML=state.saved.notes.map(n=>`<article class="note-item" data-id="${n.id}"><header><b>${esc(n.personName||'General')}</b><button class="status-btn" data-delete>Delete</button></header><p>${esc(n.text)}</p></article>`).join('')||'<div class="evidence-rule"><span>No saved notes yet.</span></div>';box.querySelectorAll('.note-item').forEach(el=>el.querySelector('[data-delete]').onclick=()=>{const id=Number(el.dataset.id);state.saved.notes=state.saved.notes.filter(n=>n.id!==id);save();renderSaved()})}
function renderWatch(){const box=$('#watchList');box.innerHTML=state.saved.watch.map(w=>`<button class="watch-item" data-person="${esc(w.id)}"><b>${esc(w.name)}</b><span>Research →</span></button>`).join('')||'<div class="evidence-rule"><span>No unresolved people on your watchlist yet.</span></div>';box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{selectPerson(b.dataset.person,false);showTab('ai')})}
function saveNote(){const text=$('#noteText').value.trim();if(!text)return;const p=selected();state.saved.notes.unshift({id:Date.now(),text,personId:p?.id||null,personName:p?.name||'General',created:new Date().toISOString()});save();$('#noteText').value='';closeModal('noteModal');renderSaved();toast('Research note saved')}
function exportBackup(){const payload={product:'Rootline AI Genealogy',version:2,exported:new Date().toISOString(),selected:state.selected,saved:state.saved};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`rootline-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Backup exported')}
async function importBackup(file){try{const x=JSON.parse(await file.text());if(!x.saved)throw Error();state.saved={notes:Array.isArray(x.saved.notes)?x.saved.notes:[],inbox:Array.isArray(x.saved.inbox)?x.saved.inbox:[],watch:Array.isArray(x.saved.watch)?x.saved.watch:[]};save();renderSaved();renderInbox();toast('Backup restored')}catch{toast('That backup file could not be read')}}

function wire(){$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#personPill').onclick=$('#changePerson').onclick=()=>openModal('personModal');$('#treeSearch').oninput=e=>renderPeople(e.target.value);$('#modalSearch').oninput=e=>renderModalPeople(e.target.value);$('#clearChat').onclick=clearChat;$('#composer').onsubmit=e=>{e.preventDefault();const t=$('#prompt').value.trim();if(!t)return;$('#prompt').value='';sendAI(t)};$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$$('.quick').forEach(b=>b.onclick=()=>{const id=b.dataset.tool;if(id==='record'&&!state.attachment){$('#attachmentInput').click();toast('Attach a record first');return}if(id==='records')$('#webMode').checked=true;sendAI(quickPrompts[id],b.querySelector('b').textContent)});$('#attachmentInput').onchange=e=>chooseFile(e.target.files?.[0]);$('#removeAttachment').onclick=removeAttachment;['recordChoose','uploadRecord'].forEach(id=>$('#'+id).onclick=()=>$('#attachmentInput').click());const drop=$('#recordDrop');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.style.borderColor='rgba(217,181,109,.55)'}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.style.borderColor=''}));drop.addEventListener('drop',e=>chooseFile(e.dataTransfer.files?.[0]));$('#watchCurrent').onclick=watchCurrent;$('#newNote').onclick=()=>openModal('noteModal');$('#saveNote').onclick=saveNote;$('#exportBackup').onclick=exportBackup;$('#backupInput').onchange=e=>importBackup(e.target.files?.[0]);$('#micBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Voice dictation is not available in this browser');return}const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{$('#prompt').value=($('#prompt').value+' '+e.results[0][0].transcript).trim()};r.onerror=()=>toast('Voice dictation could not start');r.start();toast('Listening…')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal').forEach(m=>m.classList.add('hidden'))});}

async function init(){loadSaved();wire();renderSaved();renderInbox();renderRecordCurrent();await loadTree()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
